program: train.py
method: bayes  # or 'random', 'grid'
metric:
  name: loss
  goal: minimize
parameters:
  optimizer:
    values: ["sgd", "adam", "adagrad"]
  learning_rate:
    min: 0.0001
    max: 0.1
